version: 2
jobs:
   test:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: notacommand
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: echo "hello world"

  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test